version: "2"
run:
  concurrency: 16
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - goconst
    - misspell
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of .*log\.Logger\)\.Log\x60 is not checked
      - path: (.+)\.go$
        text: Error return value of .*.Log.* is not checked
      - path: (.+)\.go$
        text: '"io/ioutil" has been deprecated'
      - path: (.+)\.go$
        text: rand.Seed has been deprecated
    paths:
      - pkg/ingester/checkpoint.pb.go
      - pkg/logproto/logproto.pb.go
      - pkg/logql/expr.y.go
      - pkg/logql/log/jsonexpr/jsonexpr.y.go
      - pkg/logql/stats/stats.pb.go
      - pkg/querier/queryrange/queryrange.pb.go
      - pkg/valitail/server/ui/assets_vfsdata.go
      - win_eventlog$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/credativ/vali/pkg
  exclusions:
    generated: lax
    paths:
      - pkg/ingester/checkpoint.pb.go
      - pkg/logproto/logproto.pb.go
      - pkg/logql/expr.y.go
      - pkg/logql/log/jsonexpr/jsonexpr.y.go
      - pkg/logql/stats/stats.pb.go
      - pkg/querier/queryrange/queryrange.pb.go
      - pkg/valitail/server/ui/assets_vfsdata.go
      - win_eventlog$
      - third_party$
      - builtin$
      - examples$
